alias g "git"
alias gco "git checkout"
alias gl "git pull"
alias gst "git status"
alias gaa "git add --all"
alias ga "git add"
alias gr "git remote"
alias gb "git branch"
alias gc "git commit"
alias gp "git push"
alias gcm "git checkout master"
alias gcr "git checkout release"

alias vim "vim -u ~/.config/nvim/init.vim"
alias vi "vim -u ~/.config/nvim/init.vim"
